# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches: [ master ]

jobs:

  check:
    runs-on: ubuntu-latest
    outputs:
      changes_found: ${{ steps.validate.outputs.found }}
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          # increase in the event of changes to git submodules
          fetch-depth: 5
      - id: validate
        run: |
          echo "=============== File Changes ==============="
          git diff --name-only HEAD^ HEAD

          echo "========== Verifying File Paths =========="
          git diff --name-only HEAD^ HEAD > files.txt

          correct_file_location=0
          while IFS= read -r file
          do
            echo $file
            if [[ $file != predictor/* ]]; then
              echo "This modified file is not under the 'predictor' folder."
              if [[ $file != tests/* ]]; then
                echo "This modified file is not under the 'tests' folder."
              else
                correct_file_location=1
              fi
            else
              correct_file_location=1
            fi
          done < files.txt

          if [ $correct_file_location == 1 ]; then
            echo "::set-output name=found::true"
          else
            echo "::set-output name=found::false"
          fi

  tests:
    needs: check
    if: needs.check.outputs.changes_found == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
          python-version: "3.9"
    - name: Local install
      run: |
        python -m pip install . --upgrade
#     - name: Install Test Deps
#       run: |
#         python -m pip install pytest coverage pytest-cov
#     - name: Tests
#       run: |
#         pytest --cov=tests
